name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup Deno
        uses: denoland/setup-deno@e95548e56dfa95d4e1a28d6f422fafe75c4c26fb # v2.0.3
        with:
          deno-version: v2.x

      - name: Install dependencies
        run: deno install

      - name: Build project
        run: deno task build

      - name: Verify dist directory
        run: |
          echo "Contents of dist directory:"
          ls -la dist/

      - name: Extract version from tag
        id: extract_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        uses: softprops/action-gh-release@72f2c25fcb47643c292f7107632f7a47c1df5cd8 # v2.3.2
        with:
          files: |
            dist/main.js
            dist/manifest.json
            dist/styles.css
          body: |
            # Weekly Summary Generator v${{ steps.extract_version.outputs.VERSION }}

            Obsidianプラグイン「Weekly Summary Generator」のリリースです。

            ## インストール方法
            1. 添付の `main.js` / `manifest.json` / `styles.css` をダウンロード
            2. Obsidianの設定 > Community plugins > フォルダアイコンをクリック
            3. プラグインフォルダに3ファイルを配置（既存ファイルは上書き）
            4. プラグインを有効化

            ## 変更内容
            このリリースの変更内容については、[コミット履歴](https://github.com/${{ github.repository }}/compare/v${{ steps.extract_version.outputs.VERSION }}...HEAD)をご確認ください。
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
