name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Install dependencies
        run: deno install

      - name: Build project
        run: deno task build

      - name: Verify dist directory
        run: |
          echo "Contents of dist directory:"
          ls -la dist/

      - name: Extract version from tag
        id: extract_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Create release zip
        run: |
          cd dist
          zip -r ../weekly-summary-${{ steps.extract_version.outputs.VERSION }}.zip .
          cd ..
          echo "Created weekly-summary-${{ steps.extract_version.outputs.VERSION }}.zip"
          ls -la *.zip

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: weekly-summary-${{ steps.extract_version.outputs.VERSION }}.zip
          body: |
            # Weekly Summary Generator v${{ steps.extract_version.outputs.VERSION }}
            
            Obsidianプラグイン「Weekly Summary Generator」のリリースです。
            
            ## インストール方法
            1. 添付のzipファイルをダウンロード
            2. Obsidianの設定 > Community plugins > フォルダアイコンをクリック
            3. zipファイルを解凍してプラグインフォルダに配置
            4. プラグインを有効化
            
            ## 変更内容
            このリリースの変更内容については、[コミット履歴](https://github.com/${{ github.repository }}/compare/v${{ steps.extract_version.outputs.VERSION }}...HEAD)をご確認ください。
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
